---
- name: Provision the APP
  hosts: [all]
  any_errors_fatal: true
  gather_facts: false
  roles:
    # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- 
    # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- 
    # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- 
    # --- 
    # B.O.M.:
    # ----
    # Provisions the App, by:
    # + Building APP Image
    # + Creating and starting an APP container
    # 
    # Inside the dreated container, you can check the tomcat exporter exposed metrics:
    # -- 
    # docker exec -it pestoapp bash -c 'curl http://127.0.0.1:8088/metrics'
    - role: build_app
    - role: start_app
      force_recreate: true
    # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- 
    # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- 
    # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- 
    # # --- 
    # # B.O.M.:
    # # ----
    # # Blablabla
    # # + this
    # # + that
    # - role: myrole