---
- name: Provision the Monitoring Stack
  hosts: [all]
  any_errors_fatal: true
  gather_facts: false
  roles:
    # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- 
    # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- 
    # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- 
    # --- 
    # B.O.M.:
    # ----
    # Provisions the Monitoring Stack, by:
    # + Git cloning the repository
    # + Running Docker Compose UP
    # 
    # 
    - role: monitoring
    # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- 
    # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- 
    # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- # --- 
    # # --- 
    # # B.O.M.:
    # # ----
    # # Blablabla
    # # + this
    # # + that
    # - role: myrole